test

diff --git a/.github/workflows/cibuildwheel.yml b/.github/workflows/cibuildwheel.yml
--- a/.github/workflows/cibuildwheel.yml
+++ b/.github/workflows/cibuildwheel.yml
@@ -15,7 +15,7 @@ on:
 
 jobs:
   build_wheels_mac:
-    name: Build ${{ matrix.py }} wheels on ${{ matrix.os }}
+    name: Build ${{ matrix.py }}-${{ matrix.cibw_arch }} wheels on ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -43,30 +43,34 @@ jobs:
         run: |
           command -v conda && ret=$? || ret=$?
           echo "CONDA_INSTALLED=$ret" >> $GITHUB_ENV
+          if [[ "$CONDA_INSTALLED" == "1" ]]; then
+              test -d /usr/local/miniconda
+              echo "CONDA_HOME=/usr/local/miniconda" >> $GITHUB_ENV
+          fi
 
-      - name: Install conda for macos arm64
-        if: ${{ matrix.cibw_arch == 'arm64' }}
-        run: |
-          set -ex
-          # check assumption that conda isn't already installed
-          [[ "$CONDA_INSTALLED" == "0" ]] || exit 1
-          command -v conda && exit 1
-          # macos arm64 runners do not have conda installed
-          MINIFORGE_URL="https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Mambaforge-23.11.0-0-MacOSX-arm64.sh"
-          curl -L --retry 10 $MINIFORGE_URL -o miniforge.sh
-          # install miniforge
-          MINIFORGE_PATH=$HOME/miniforge
-          bash ./miniforge.sh -b -p $MINIFORGE_PATH
-          # echo "$MINIFORGE_PATH/bin" >> $GITHUB_PATH
-          echo "CONDA_HOME=$MINIFORGE_PATH" >> $GITHUB_ENV
+      # - name: Install conda for macos arm64
+      #   if: ${{ matrix.cibw_arch == 'arm64' }}
+      #   run: |
+      #     set -ex
+      #     # check assumption that conda isn't already installed
+      #     [[ "$CONDA_INSTALLED" == "0" ]] || exit 1
+      #     command -v conda && exit 1
+      #     # macos arm64 runners do not have conda installed
+      #     MINIFORGE_URL="https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Mambaforge-23.11.0-0-MacOSX-arm64.sh"
+      #     curl -L --retry 10 $MINIFORGE_URL -o miniforge.sh
+      #     # install miniforge
+      #     MINIFORGE_PATH=$HOME/miniforge
+      #     bash ./miniforge.sh -b -p $MINIFORGE_PATH
+      #     # echo "$MINIFORGE_PATH/bin" >> $GITHUB_PATH
+      #     echo "CONDA_HOME=$MINIFORGE_PATH" >> $GITHUB_ENV
 
-      - name: Set conda environment for existing conda installation
-        if: ${{ matrix.cibw_arch != 'arm64' }}
-        run: |
-          # check assumption that conda is already installed
-          [[ "$CONDA_INSTALLED" == "1" ]] || exit 1
-          test -d /usr/local/miniconda
-          echo "CONDA_HOME=/usr/local/miniconda" >> $GITHUB_ENV
+      # - name: Set conda environment for existing conda installation
+      #   if: ${{ matrix.cibw_arch != 'arm64' }}
+      #   run: |
+      #     # check assumption that conda is already installed
+      #     [[ "$CONDA_INSTALLED" == "1" ]] || exit 1
+      #     test -d /usr/local/miniconda
+      #     echo "CONDA_HOME=/usr/local/miniconda" >> $GITHUB_ENV
 
       - name: Build wheels for CPython (macOS)
         run: |
